name: Building, testing and assembling jar-file
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build, test and assemble jar
        run: ./gradlew build test bootJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: droidherd-service
          path: app/build/libs/droidherd-service.jar
